### ISSUE TITLE
Support placement constraints/strategy in Procfile

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#1057]
We don't have an issue tracking this yet. Placement constraints are a great way to specify the machine/security requirements for an application http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html

This should be supported in the Procfile with something like this:

```yml
web:
  placement:
    constraints:
      - type: memberOf
        expression: "attribute:ecs.instance-type =~ t2.*"
    strategy:
      - type: spread
        field: "attribute:ecs.availability-zone"
```
