### ISSUE TITLE
Ability to set "exposure" by process

### ISSUE THREAD

**Issue by iserko** [remind101/empire#1076]
Currently "exposure" as it is phrased in the code is controlled by running:
- `emp domain-add <domain>` which makes ELB/ALB `internet-facing`
- `emp domain-remove <domain>` which makes ELB/ALB `internal` (or if you never use domain-add for an app

That setting is applied across the whole application and has no ability to set it per web process.

What I would like to see is to be able to control it via the Procfile using `EMPIRE_X_EXPOSURE` if it existed:
```
# internal
qint:
  command: ./bin/web
  ports:
    - "80:8080"
  environment:
    EMPIRE_X_LOAD_BALANCER_TYPE: "alb"
    EMPIRE_X_EXPOSURE: "internal"

# external
qext:
  command: ./bin/web
  ports:
    - "80:8080"
  environment:
    EMPIRE_X_LOAD_BALANCER_TYPE: "alb"
    EMPIRE_X_EXPOSURE: "internet-facing"  
```
