### ISSUE TITLE
emp cert-attach errors with `error: no stack for app found` on a new app

### ISSUE THREAD

**Issue by iserko** [remind101/empire#1080]
If you have an extended Procfile as follows:
```
myapp:
  command: ./bin/web
  ports:
    - "443:8080"
  environment:
    EMPIRE_X_LOAD_BALANCER_TYPE: "alb"
```

and you do:
```
% emp create myapp
% emp deploy -a myapp myapp/myapp:latest
# the command returns an error
error: the myapp process does not have a certificate attached
```

If you try to do `emp cert-attach -a myapp -p myapp <cert_arn>` at that point you keep getting `error: no stack for app found`.
I checked CloudFormation and there was no stack triggered for the app.
Seems like the failed deploy still triggers something, but doesn't reset it in case of a cert failure.
Then when you try running `cert-attach`, it wants to do an update of the stack, but there isn't one.

Workaround: destroy the app and recreate it and this time do `cert-attach` before `deploy`
