### ISSUE TITLE
Extend Procfile health check for application with ALB 

### ISSUE THREAD

**Issue by darkamenosa** [remind101/empire#1102]
My application has an `/health` endpoint. After public the application by using **ALB**, I got my the app's url. However, when I accessed the url, I always got 503 status. The default health check url for **target group** is `/`. I went to AWS console and edited health check url, everything worked fine.
I wondered if there is anyway to configure health check using the Procfile. I searched the docs and this repository and found 2 ways: 
**First**: (from Extended Procfile Roadmap)
```
web:
  command: java -jar account-service.jar
  expose:
    type: http
    external: true
    check:
      path: /health
      healthy_threshold: 2
      unhealthy_threshold: 10
```

**Second**: (from some commit)
```
web:
  command: java -jar account-service.jar
  health_checks:
    path: /health"
```

However, these 2 ways are not work for me. The default health check url always is `/`. Do I miss anything here? Please point out if I'm wrong. Thanks!
