### ISSUE TITLE
Empire configuration

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#415]
We have a lot of flags now, which gets a little hard to document. Might be good to use something like https://github.com/spf13/viper to parse a config file.

```yaml
db:
  url: postgres://localhost
  migrations: ./migrations
github:
  client_id: abcd
  client_secret: secret
  organization: remind101
docker:
  organization: remind101
  host: unix://var/run/docker.sock
  cert:
  auth:
    user: ejholmes
    password: foobar
elb:
  security_groups:
    private: sg-dd92beb9
    public: sg-d092beb4
ecs:
  cluster: empire-soephahrah
  service_role: empire-soephahrah-ServiceRole-1X0F28VCI8GRS
ec2:
  subnets:
    private:
      - subnet-25296f52
      - subnet-de5dc787
    public:
      - subnet-25296f52
      - subnet-de5dc787
```

Just a nice to have. Would be good to support both config file and flags.
