### ISSUE TITLE
Better security around `emp run`

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#966]
`emp run` grants a lot of power and flexibility, but can become difficult to track what people are doing.

It may be nice to provide an option to whitelist certain processes in the extended Procfile as "runnable" processes.

So instead of allowing any command to be run, you would add a command to `Procfile` and that command could then be run with `emp run`. For example:

```yaml
migrate:
  command: bundle exec rake db:migrate:up
  run: true
console:
  command: bundle exec rails console
  run: true
psql:
  command: ./bin/psql
  run: true
```

Doing this would allow you to whitelist "safe" commands, and disallow things like `emp run bash`.

Obviously, this isn't perfect, since if you allow things like `rails console`, someone can just `Kernel.system`, so this would be mostly there to prevent accidents, and provide a documented list of "operational" commands for the service.
