### ISSUE TITLE
Dual ELB/ALB

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#991]
https://github.com/remind101/empire/pull/969 added support for switching to ALB, but in a production system, switching would incur downtime, especially if the application is public.

Instead, we should support a "migration" phase where Empire creates both an ELB and an ALB with different CNAME's, then we can swap between each by changing DNS.

**Comment by ejholmes** [comment]
Probably makes the most sense to make this part of the extended procfile, so you can just add a new web proc that uses an ALB:

```yaml
web:
  command: ./bin/web
web2:
  command: ./bin/web
  load_balancer_type: alb
```
